services:
  web:
    container_name: web
    # image: nextjs:latest-230818
    image: wkdms3509/docker-hub-test:nextjs-230818
    build:
      context: ./cocktail-app
      # dockerfile: Dockerfile.production
    tty: true
    restart: always
    command: npm run dev
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    volumes:
      - "./cocktail-app:/app"
    ports:
      - "3000:3000"
    networks:
      - my-bridge-network

  mysql:
    container_name: mysql
    platform: linux/x86_64
    # image: mysql:8.0.34
    image: wkdms3509/docker-hub-test:mysql-8.0.34
    restart: always
    volumes:
      - ./cocktail-app/src/mysql/init.d:/docker-entrypoint-initdb.d
      - ./cocktail-app/src/mysql/conf.d:/etc/mysql/conf.d
      - ./cocktail-app/src/mysql/data:/var/lib/mysql
      - ./cocktail-app/src/data:/data
    environment:
      - MYSQL_DATABASE=testcocktailsdb
      - MYSQL_ROOT_PASSWORD=sorksnrnrp
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=engineer
      - TZ=Asia/Seoul
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - my-bridge-network

  selenium:
    container_name: selenium_chrome
    image: wkdms3509/docker-hub-test:seleniarm-latest
    build:
      context: ./crawler
    shm_size: 2gb
    environment:
      - TZ=Asia/Seoul
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge
